#!/bin/bash
# Author: ghostwan@gmail.com

if [ $# -ne 1 ]; then
  echo " Usage: ${0##*/} repo_name"
  echo
  echo " Description: Create a GitHub repository with an MIT license"
  exit 1
fi

repo_name=$1

echo "Creating repository '$repo_name' on GitHub..."
gh repo create "$repo_name" --public --license mit --clone

if [ $? -eq 0 ]; then
  echo "Repository '$repo_name' created and cloned successfully!"
else
  echo "Failed to create repository '$repo_name'"
  exit 1
fi
