#!/bin/bash

function println() {
  printf "\033[0;33m $1 \033[0m\n"
}

function getLastTags() {
  number=5
  if [ $# -eq 1 ]; then
    number=$1
  fi
  git tag | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -$number
}

function displayLastTagHelp() {
  git fetch --all
  last_tag=$(getLastTags 1)
  println "Example: ${0##*/} ${last_tag%.*}.$((${last_tag##*.} + 1)) $1"

  println "Last tags created:"
  println """
$(getLastTags 5)
  """
}

function question_No_or_yes() {
  printf "\033[0;41m $1 \033[0m"
  printf "(\033[0;91m[N]o\033[0m"
  read -p " or [y]es): "
  case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
  y | yes) return 0 ;;
  *)       return 1 ;;
  esac
}

if [ $# -ne 1 ]; then
  echo " Usage: ${0##*/} tag_id"
  echo
  echo " Decription: This script will remove the tag locally and in remote"
  displayLastTagHelp
  exit 0
fi
tag=$1
if question_No_or_yes "remove the tag $1 locally and remotely?"
then
    git tag -d $tag
    git push origin --delete $tag
fi

