#!/bin/sh

fetch=false
check=false

display_usage() {
  echo "Update the workspace; add and refresh repositories from .projects.gws"
  echo
  echo "Usage: ${0##*/} [-h] [-f] [-c]"
  echo
  echo " -h     Display usage instructions"
  echo " -f     Fetch the workspace configuration and repositories"
  echo " -c     Check worksapce status"
  echo
}

while getopts "h?fc" opt; do
    case "$opt" in
    h | \?)
        display_usage
        exit 0
        ;;
    f)
        fetch=true
        ;;
    c)
        check=true
        ;;
    esac
done
shift $((OPTIND - 1))
[ "${1:-}" = "--" ] && shift
remaining_args="$@"

if [ $fetch = true ]; then
    git fetch --all
    git pull --rebase
fi

rm .cache.gws*
gws update $remaining_args

if [ $fetch = true ]; then
    gws ff $remaining_args
fi

if [ $check = true ]; then
    gws check $remaining_args
fi

