#!/bin/bash

display_usage() {
  echo "Add existing repository into the workspace (.projects.gws)"
  echo
  echo "Usage: ${0##*/} [-h] <local-path> <repo-url>"
  echo
  echo " -h     Display usage instructions"
  echo
  echo "Example: ${0##*/} projects/android/ https://github.com/myuser/my-super-sample.git"
}

function print_error() {
    printf "\033[0;31m$1\033[0m\n"
}
function print_ok() {
    printf "\033[0;32mOK\033[0m\n"
}
i="\033[0;33m"
e="\033[0m"

OPTIND=1
while getopts "h?s" opt; do
    case "$opt" in
        h | \?) display_usage >&2; exit 0;;
    esac
done
shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift
if [ $# -le 1 ]; then
    display_usage
    exit 1
fi

localpath=$1
url=$2
reponame=${url##*/}
reponame=${reponame%.*}

result=$(cat $WORK/.projects.gws | grep "$localpath/$reponame")
if [ -n "$result" ]; then
    print_error "Repository $localpath/$reponame already exist in workspace!"
    exit 1
fi

printf "Adding path $i$localpath/$reponame$e for repo $i$url$e in .project.gws..."

if [ -n "$(tail -c 1 "$WORK/.projects.gws")" ]; then
    echo "" >> $WORK/.projects.gws
fi

echo "$localpath/$reponame | $url" >> $WORK/.projects.gws
print_ok

printf "Fetching repo $i$reponame$e...\n"
gws-update