#!/bin/sh

fetch=false
check=false
while getopts "h?fc" opt; do
    case "$opt" in
    h | \?)
        echo "Usage: gws-update [-h] [-f] [-c] \n Options:\n -h Show this screen \n -f fetch the workspace \n -c check the workspace" >&2
        exit 0
        ;;
    f)
        fetch=true
        ;;
    c)
        check=true
        ;;
    esac
done
shift $((OPTIND - 1))
[ "${1:-}" = "--" ] && shift
remaining_args="$@"

if [ $fetch = true ]; then
    git fetch --all
    git pull --rebase
fi

rm .cache.gws*
gws update $remaining_args

if [ $fetch = true ]; then
    gws ff $remaining_args
fi

if [ $check = true ]; then
    gws check $remaining_args
fi

