#!/bin/bash
# Author: ghostwan@gmail.com

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters!"
    echo "Usage: openssl_test_cipher <server>"
    echo "Example: openssl_test_cipher 127.0.0.1:443"
    exit 1
fi

# OpenSSL requires the port number.
SERVER=$1
DELAY=1
ciphers=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g')

echo Obtaining cipher list from $(openssl version).

for cipher in ${ciphers[@]}
do
echo -n Testing $cipher...
result=$(echo -n | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
if [[ "$result" =~ ":error:" ]] ; then
  error=$(echo -n $result | cut -d':' -f6)
  printf "\033[0;31mKO\033[0m ($error)\n"
else
  if [[ "$result" =~ "Cipher is ${cipher}" || "$result" =~ "Cipher    :" ]] ; then
    printf "\033[0;32mOK\033[0m\n"
  else
    printf "\033[0;33mUNKNOWN RESPONSE\033[0m $result \n"
  fi
fi
sleep $DELAY
done